from app.core.prompts.en import (
    STORY_GENERATION_PROMPT_TEMPLATE_EN,
    STORY_CONTINUATION_PROMPT_TEMPLATE_EN,
    STORY_CONCLUSION_PROMPT_TEMPLATE_EN,
)
from app.core.prompts.uk import (
    STORY_GENERATION_PROMPT_TEMPLATE_UK,
    STORY_CONTINUATION_PROMPT_TEMPLATE_UK,
    STORY_CONCLUSION_PROMPT_TEMPLATE_UK,
)
from app.core.prompts.replicate_image import (
    COVER_IMAGE_PROMPT_TEMPLATE_EN,
)

PROMPTS = {
    "STORY_GENERATION_PROMPT_TEMPLATE_EN": STORY_GENERATION_PROMPT_TEMPLATE_EN,
    "STORY_CONTINUATION_PROMPT_TEMPLATE_EN": STORY_CONTINUATION_PROMPT_TEMPLATE_EN,
    "STORY_CONCLUSION_PROMPT_TEMPLATE_EN": STORY_CONCLUSION_PROMPT_TEMPLATE_EN,

    "STORY_GENERATION_PROMPT_TEMPLATE_UK": STORY_GENERATION_PROMPT_TEMPLATE_UK,
    "STORY_CONTINUATION_PROMPT_TEMPLATE_UK": STORY_CONTINUATION_PROMPT_TEMPLATE_UK,
    "STORY_CONCLUSION_PROMPT_TEMPLATE_UK": STORY_CONCLUSION_PROMPT_TEMPLATE_UK,

    "COVER_IMAGE_PROMPT_TEMPLATE_EN": COVER_IMAGE_PROMPT_TEMPLATE_EN,
}
