import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
STORY_GENERATION_PROMPT_TEMPLATE = os.getenv("STORY_GENERATION_PROMPT_TEMPLATE")
STORY_CONTINUATION_PROMPT_TEMPLATE = os.getenv("STORY_CONTINUATION_PROMPT_TEMPLATE")