STORY_GENERATION_PROMPT_TEMPLATE = "STORY_GENERATION_PROMPT_TEMPLATE"
STORY_CONTINUATION_PROMPT_TEMPLATE = "STORY_CONTINUATION_PROMPT_TEMPLATE"
STORY_CONCLUSION_PROMPT_TEMPLATE = "STORY_CONCLUSION_PROMPT_TEMPLATE"

AI_MODEL = "gpt-4o-mini"
PRO_AGENT_MODEL = "gpt-4o-2024-08-06"