STORY_GENERATION_PROMPT_TEMPLATE = {
    "en": "STORY_GENERATION_PROMPT_TEMPLATE_EN",
    "uk": "STORY_GENERATION_PROMPT_TEMPLATE_UK",    
}
STORY_CONTINUATION_PROMPT_TEMPLATE = {
    "en": "STORY_CONTINUATION_PROMPT_TEMPLATE_EN",
    "uk": "STORY_CONTINUATION_PROMPT_TEMPLATE_UK",
}
STORY_CONCLUSION_PROMPT_TEMPLATE = {
    "en": "STORY_CONCLUSION_PROMPT_TEMPLATE_EN",
    "uk": "STORY_CONCLUSION_PROMPT_TEMPLATE_UK",
}

AI_MODEL = "gpt-4o"
PRO_AGENT_MODEL = "gpt-4o"

FLUX_SCHNELL_PREDICTIONS_URL = "https://api.replicate.com/v1/models/black-forest-labs/flux-schnell/predictions"